apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        track: stable
    spec:
      containers:
        - name: nginx
          image: "gcr.io/main-testing/app:v1"
          ports:
            - name: http
              containerPort: 80
